server:
  port: 8081

spring:
  application:
    name: gestiondepedidos-dev

  datasource:
    url: jdbc:h2:mem:gestiondepedidos
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    '[primerspringboot.com.gestiondepedidos]': DEBUG
    '[org.springframework.web]': WARN